name: Test

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  kotest:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Test
        env:
          DB_TEST_IP: ${{ secrets.DB_TEST_IP }}
          DB_TEST_PORT: ${{ secrets.DB_TEST_PORT }}
          DB_TEST_PWD: ${{ secrets.DB_TEST_PWD }}
          DB_TEST_USER: ${{ secrets.DB_TEST_USER }}
          TEST_DB: ${{ secrets.TEST_DB }}
          TEST_DB_ID: ${{ secrets.TEST_DB_ID }}
        run: gradle kotest

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}